=== tesiakosmalski/StructuredAuthoring/XML - 2010/2010_DTD.dtd
<!ELEMENT resident (name, location, contact, socialmedia, medium, externalurl, artimage)>
<!ATTLIST resident type (artist|designer|collective) #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name (first_last|studio) "first_last">

<!ELEMENT location (#PCDATA)>
<!ATTLIST location type (building|suite) "suite">

<!ELEMENT contact (#PCDATA)>
<!ATTLIST contact type (email|phone) "email">

<!ELEMENT socialmedia (#PCDATA)>
<!ATTLIST socialmedia type (instagram|facebook|pinterest) "instagram">

<!ELEMENT medium (#PCDATA)>
<!ELEMENT externalurl (#PCDATA)>

<!--this has to become a jpg somehow-->
<!ELEMENT artimage (#PCDATA)>


<!--EVENTS ELEMENTS-->
<!ELEMENT events (eventstitle, type, Summary, Dates, Times, EventImage, Caption)>
<!ELEMENT eventstitle (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT Summary (#PCDATA)>
<!ELEMENT Dates (#PCDATA)>
<!ELEMENT Times (#PCDATA)>
<!ELEMENT EventImage (image?)>
<!ELEMENT Caption (#PCDATA)>

<!ELEMENT year (#PCDATA)>

=== tesiakosmalski/StructuredAuthoring/XML - 2010/EventsSIMPLIFIED.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="styles.css"?>

<!DOCTYPE events SYSTEM "2010_DTD.dtd">

	<events>
		<eventtitle>Art a Whirl</eventtitle>
		<type>Event</type>
		<Summary>This is a big event! Stop by!</Summary>
			<Dates>October 12-14, 2019</Dates>
			<Times>11AM-9PM</Times>
			<EventImage>abc.jpg</EventImage>
			<Caption>Look at all the artists in the building.</Caption>


		<eventtitle>Art a Whirl
			<type>Event</type>
		<Summary>This is a big event! Stop by!</Summary>
			<Dates>October 12-14, 2019</Dates>
			<Times>11AM-9PM</Times>
			<EventImage>xyz.jpg</EventImage>
			<Caption>Look at all the artists in the building.</Caption>
		</eventtitle>

	</events>
